### ISSUE TITLE
SMPL version

### ISSUE THREAD

**Issue by boqian-li** [anticdimi/CloSe#7]
Hi, thanks for your great work. Could you please tell me the version and the gender of SMPL you used to fit Close-Di?

**Comment by anticdimi** [comment]
Hi @boqian-li ,

1. We used the manually-annotated gender for each scan.
2. We used SMPL v1.1 with 300 betas for registering and fitting, but we released the data with only 10 beta coefficients since those carry the most information.

I will close this issue, but please feel free to reopen it if needed.
